runners:
  hadoop_local:
    type: hadoop
    hadoop_bin: /usr/local/hadoop/bin/hadoop
    hadoop_streaming_jar: /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-*.jar

    hadoop_extra_args:
      - -Dmapreduce.job.reduces=10
      - -Dmapreduce.input.fileinputformat.split.maxsize=67108864  # 64 MB
      - -Dmapreduce.map.memory.mb=2048
      - -Dmapreduce.reduce.memory.mb=4096
      - -Dmapreduce.map.java.opts=-Xmx1638m
      - -Dmapreduce.reduce.java.opts=-Xmx3277m
      - -Dmapreduce.map.speculative=false
      - -Dmapreduce.reduce.speculative=false
      - -Ddfs.blocksize=134217728  # 128MB
