name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint analysis
        run: |
          pylint_score=$(pylint --exit-zero src/ tests/ | grep -oP 'at \K\d+\.\d+')
          echo "Pylint score: $pylint_score"
          awk -v score="$pylint_score" 'BEGIN {exit !(score >= 0)}'

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.9"
      - run: pip install -r requirements.txt
      
      - name: Run and verify tests
        run: |
          # Running test files
          pytest -s > pytest_output.log
          
          # Check output
          for test_file in "cleaner" "mapper_sentiment" "reducer_sentiment" "reader"; do
            if grep -q "Test start" pytest_output.log; then
              echo "Connect logic success for $test_file"
            else
              echo "Connect logic failed for $test_file"
              exit 1
            fi
          done